// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MultiResponsePage_screen_init(void)
{
    ui_MultiResponsePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MultiResponsePage, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_MultiResponsePage, lv_color_hex(0x343541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MultiResponsePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QueryResponsePanel = lv_obj_create(ui_MultiResponsePage);
    lv_obj_set_width(ui_QueryResponsePanel, 337);
    lv_obj_set_height(ui_QueryResponsePanel, 188);
    lv_obj_set_x(ui_QueryResponsePanel, -7);
    lv_obj_set_y(ui_QueryResponsePanel, -25);
    lv_obj_set_align(ui_QueryResponsePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_QueryResponsePanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_QueryResponsePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_QueryResponsePanel, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_QueryResponsePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QueryResponsePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_QueryResponsePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_QueryResponsePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QueryPanel = lv_obj_create(ui_QueryResponsePanel);
    lv_obj_set_width(ui_QueryPanel, 316);
    lv_obj_set_height(ui_QueryPanel, 70);
    lv_obj_set_x(ui_QueryPanel, 0);
    lv_obj_set_y(ui_QueryPanel, -50);
    lv_obj_set_align(ui_QueryPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_QueryPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_QueryPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QueryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_QueryPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_QueryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_querybox1 = lv_textarea_create(ui_QueryPanel);
    lv_obj_set_width(ui_querybox1, 269);
    lv_obj_set_height(ui_querybox1, 63);
    lv_obj_set_x(ui_querybox1, 22);
    lv_obj_set_y(ui_querybox1, 0);
    lv_obj_set_align(ui_querybox1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_querybox1, "Query");
    lv_obj_add_state(ui_querybox1, LV_STATE_DISABLED); /// States
    lv_obj_set_style_bg_color(ui_querybox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_querybox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_querybox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_querybox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_querybox1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_querybox1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_queyboximg = lv_img_create(ui_QueryPanel);
    lv_img_set_src(ui_queyboximg, &ui_img_116700466);
    lv_obj_set_width(ui_queyboximg, LV_SIZE_CONTENT);  /// 24
    lv_obj_set_height(ui_queyboximg, LV_SIZE_CONTENT); /// 24
    lv_obj_set_x(ui_queyboximg, -134);
    lv_obj_set_y(ui_queyboximg, -7);
    lv_obj_set_align(ui_queyboximg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_queyboximg, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_queyboximg, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ResponsePanel = lv_obj_create(ui_QueryResponsePanel);
    lv_obj_set_width(ui_ResponsePanel, 320);
    lv_obj_set_height(ui_ResponsePanel, LV_SIZE_CONTENT); /// 100
    lv_obj_set_x(ui_ResponsePanel, -263);
    lv_obj_set_y(ui_ResponsePanel, 38);
    lv_obj_set_align(ui_ResponsePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResponsePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResponsePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_ResponsePanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image3 = lv_img_create(ui_ResponsePanel);
    lv_img_set_src(ui_Image3, &ui_img_1161678635);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);  /// 24
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT); /// 24
    lv_obj_set_x(ui_Image3, -135);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResponseBox = lv_textarea_create(ui_ResponsePanel);
    lv_obj_set_width(ui_ResponseBox, lv_pct(82));
    lv_obj_set_height(ui_ResponseBox, LV_SIZE_CONTENT); /// 70
    lv_obj_set_x(ui_ResponseBox, 19);
    lv_obj_set_y(ui_ResponseBox, -17);
    lv_obj_set_align(ui_ResponseBox, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ResponseBox, "Generating...");
    lv_obj_add_state(ui_ResponseBox, LV_STATE_DISABLED); /// States
    lv_obj_set_style_bg_color(ui_ResponseBox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResponseBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResponseBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResponseBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ResponseBox, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_ResponseBox, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Spinner1 = lv_spinner_create(ui_ResponsePanel, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 20);
    lv_obj_set_height(ui_Spinner1, 20);
    lv_obj_set_x(ui_Spinner1, 124);
    lv_obj_set_y(ui_Spinner1, 122);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE); /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN); /// Flags

    ui_KeyboardPanel2 = lv_obj_create(ui_MultiResponsePage);
    lv_obj_set_width(ui_KeyboardPanel2, 318);
    lv_obj_set_height(ui_KeyboardPanel2, 245);
    lv_obj_set_x(ui_KeyboardPanel2, -5);
    lv_obj_set_y(ui_KeyboardPanel2, 185);
    lv_obj_set_align(ui_KeyboardPanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_KeyboardPanel2, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_KeyboardPanel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_KeyboardPanel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_KeyboardPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_KeyboardPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_KeyboardPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_KeyboardPanel2);
    lv_obj_set_width(ui_Keyboard2, 300);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 69);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_KeyboardTextArea2 = lv_textarea_create(ui_KeyboardPanel2);
    lv_obj_set_width(ui_KeyboardTextArea2, 295);
    lv_obj_set_height(ui_KeyboardTextArea2, 34);
    lv_obj_set_x(ui_KeyboardTextArea2, 1);
    lv_obj_set_y(ui_KeyboardTextArea2, 84);
    lv_obj_set_align(ui_KeyboardTextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_KeyboardTextArea2, "Send a message");
    lv_obj_clear_flag(ui_KeyboardTextArea2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_sendButton2 = lv_btn_create(ui_KeyboardTextArea2);
    lv_obj_set_width(ui_sendButton2, 38);
    lv_obj_set_height(ui_sendButton2, 50);
    lv_obj_set_x(ui_sendButton2, 124);
    lv_obj_set_y(ui_sendButton2, 1);
    lv_obj_set_align(ui_sendButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sendButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_sendButton2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_sendButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sendButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sendButton2, &ui_img_1645855493, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_sendButton2, lv_color_hex(0xC9CADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_sendButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_sendButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_sendButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_sendButton2, lv_color_hex(0x282626), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_img_recolor_opa(ui_sendButton2, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sendButton2, ui_event_sendButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardTextArea2, ui_event_KeyboardTextArea2, LV_EVENT_ALL, NULL);
}

void create_new_query()
{
    // get the text from keytext area 2
    char *query_text = lv_textarea_get_text(ui_KeyboardTextArea2);

    lv_obj_t *new_query_panel = ui_QueryPanels[total_queries - 1];
    new_query_panel = lv_obj_create(ui_QueryResponsePanel);
    lv_obj_set_width(new_query_panel, 316);
    lv_obj_set_height(new_query_panel, 70);
    lv_obj_set_x(new_query_panel, 0);
    lv_obj_set_y(new_query_panel, -50);
    lv_obj_set_align(new_query_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(new_query_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(new_query_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(new_query_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(new_query_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(new_query_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *new_query_box = ui_QueryBoxes[total_queries - 1];
    new_query_box = lv_textarea_create(new_query_panel);
    lv_obj_set_width(new_query_box, 269);
    lv_obj_set_height(new_query_box, 63);
    lv_obj_set_x(new_query_box, 22);
    lv_obj_set_y(new_query_box, 0);
    lv_obj_set_align(new_query_box, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(new_query_box, "Query");
    lv_textarea_set_text(new_query_box, query_text);
    lv_obj_add_state(new_query_box, LV_STATE_DISABLED); /// States
    lv_obj_set_style_bg_color(new_query_box, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(new_query_box, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(new_query_box, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(new_query_box, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(new_query_box, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(new_query_box, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_t *new_query_box_img = ui_QueryImages[total_queries - 1];
    new_query_box_img = lv_img_create(new_query_panel);
    lv_img_set_src(new_query_box_img, &ui_img_116700466);
    lv_obj_set_width(new_query_box_img, LV_SIZE_CONTENT);  /// 24
    lv_obj_set_height(new_query_box_img, LV_SIZE_CONTENT); /// 24
    lv_obj_set_x(new_query_box_img, -134);
    lv_obj_set_y(new_query_box_img, -7);
    lv_obj_set_align(new_query_box_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(new_query_box_img, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(new_query_box_img, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_t *new_response_panel = ui_QueryPanels[total_queries - 1];
    new_response_panel = lv_obj_create(ui_QueryResponsePanel);
    lv_obj_set_width(new_response_panel, 320);
    lv_obj_set_height(new_response_panel, LV_SIZE_CONTENT); /// 100
    lv_obj_set_x(new_response_panel, -263);
    lv_obj_set_y(new_response_panel, 38);
    lv_obj_set_align(new_response_panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(new_response_panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(new_response_panel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(new_response_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_t *new_response_img = ui_ResponseImages[total_queries - 1];
    new_response_img = lv_img_create(new_response_panel);
    lv_img_set_src(new_response_img, &ui_img_1161678635);
    lv_obj_set_width(new_response_img, LV_SIZE_CONTENT);  /// 24
    lv_obj_set_height(new_response_img, LV_SIZE_CONTENT); /// 24
    lv_obj_set_x(new_response_img, -135);
    lv_obj_set_y(new_response_img, 0);
    lv_obj_set_align(new_response_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(new_response_img, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(new_response_img, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(new_response_img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(new_response_img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *new_response_box = lv_textarea_create(new_response_panel);
    lv_obj_set_width(new_response_box, lv_pct(82));
    lv_obj_set_height(new_response_box, LV_SIZE_CONTENT); /// 70
    lv_obj_set_x(new_response_box, 19);
    lv_obj_set_y(new_response_box, -17);
    lv_obj_set_align(new_response_box, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(new_response_box, "Generating...");
    lv_obj_add_state(new_response_box, LV_STATE_DISABLED); /// States
    lv_obj_set_style_bg_color(new_response_box, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(new_response_box, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(new_response_box, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(new_response_box, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(new_response_box, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(new_response_box, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    ui_ResponseBoxes[total_queries - 1] = new_response_box;

    lv_obj_set_parent(ui_Spinner1, new_response_panel);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);

    lv_obj_scroll_to_y(ui_QueryResponsePanel, 1000, LV_ANIM_ON);

    total_queries++;
}