// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void keyboard_pop_up_Animation(lv_obj_t *TargetObject, int delay);
void keyboard_hide_Animation(lv_obj_t *TargetObject, int delay);

// SCREEN: ui_entryPage
void ui_entryPage_screen_init(void);
lv_obj_t *ui_entryPage;
lv_obj_t *ui_chatgptdecor;
void ui_event_Suggestion2(lv_event_t *e);
lv_obj_t *ui_Suggestion2;
void ui_event_Suggestion1(lv_event_t *e);
lv_obj_t *ui_Suggestion1;
void ui_event_keyboardPanel1(lv_event_t *e);
lv_obj_t *ui_keyboardPanel1;
void ui_event_Keyboard1(lv_event_t *e);
lv_obj_t *ui_Keyboard1;
void ui_event_keyboardTextArea1(lv_event_t *e);
lv_obj_t *ui_keyboardTextArea1;
void ui_event_sendButton1(lv_event_t *e);
lv_obj_t *ui_sendButton1;

// SCREEN: ui_MultiResponsePage
void ui_MultiResponsePage_screen_init(void);
lv_obj_t *ui_MultiResponsePage;
lv_obj_t *ui_QueryResponsePanel;
lv_obj_t *ui_QueryPanel;
lv_obj_t *ui_querybox1;
lv_obj_t *ui_queyboximg;
lv_obj_t *ui_ResponsePanel;
lv_obj_t *ui_Image3;
lv_obj_t *ui_ResponseBox;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_KeyboardPanel2;
void ui_event_Keyboard2(lv_event_t *e);
lv_obj_t *ui_Keyboard2;
void ui_event_KeyboardTextArea2(lv_event_t *e);
lv_obj_t *ui_KeyboardTextArea2;
void ui_event_sendButton2(lv_event_t *e);
lv_obj_t *ui_sendButton2;
lv_obj_t *ui____initial_actions0;

lv_obj_t *ui_QueryBoxes[MAX_QUERIES];
lv_obj_t *ui_QueryPanels[MAX_QUERIES];
lv_obj_t *ui_QueryImages[MAX_QUERIES];
lv_obj_t *ui_ResponseBoxes[MAX_QUERIES];
lv_obj_t *ui_ResponsePanels[MAX_QUERIES];
lv_obj_t *ui_ResponseImages[MAX_QUERIES];

const lv_img_dsc_t *ui_imgset_55443967[1] = {&ui_img_1161678635};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void keyboard_pop_up_Animation(lv_obj_t *TargetObject, int delay)
{
      ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
      PropertyAnimation_0_user_data->target = TargetObject;
      PropertyAnimation_0_user_data->val = -1;
      lv_anim_t PropertyAnimation_0;
      lv_anim_init(&PropertyAnimation_0);
      lv_anim_set_time(&PropertyAnimation_0, 600);
      lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
      lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
      lv_anim_set_values(&PropertyAnimation_0, 130, 60);
      lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
      lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
      lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
      lv_anim_set_playback_time(&PropertyAnimation_0, 0);
      lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
      lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
      lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
      lv_anim_set_early_apply(&PropertyAnimation_0, false);
      lv_anim_start(&PropertyAnimation_0);
}
void keyboard_hide_Animation(lv_obj_t *TargetObject, int delay)
{
      ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
      PropertyAnimation_0_user_data->target = TargetObject;
      PropertyAnimation_0_user_data->val = -1;
      lv_anim_t PropertyAnimation_0;
      lv_anim_init(&PropertyAnimation_0);
      lv_anim_set_time(&PropertyAnimation_0, 600);
      lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
      lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
      lv_anim_set_values(&PropertyAnimation_0, 60, 188);
      lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
      lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
      lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
      lv_anim_set_playback_time(&PropertyAnimation_0, 0);
      lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
      lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
      lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
      lv_anim_set_early_apply(&PropertyAnimation_0, false);
      lv_anim_start(&PropertyAnimation_0);
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Suggestion2(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_CLICKED)
      {
            _ui_screen_change(&ui_MultiResponsePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MultiResponsePage_screen_init);
            lv_textarea_set_text(ui_keyboardTextArea1, lv_label_get_text(target));
            first_query_update(e);
            send_query_to_server(e);
      }
}
void ui_event_Suggestion1(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_CLICKED)
      {
            _ui_screen_change(&ui_MultiResponsePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MultiResponsePage_screen_init);
            lv_textarea_set_text(ui_keyboardTextArea1, lv_label_get_text(target));
            first_query_update(e);
            send_query_to_server(e);
      }
}
void ui_event_keyboardPanel1(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_DEFOCUSED)
      {
            keyboard_hide_Animation(ui_keyboardPanel1, 0);
      }
}
void ui_event_Keyboard1(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_RELEASED)
      {
            _ui_keyboard_set_target(ui_Keyboard1, ui_keyboardTextArea1);
            is_query_present(e);
      }
      if (event_code == LV_EVENT_READY)
      {
            keyboard_hide_Animation(ui_keyboardPanel1, 0);
      }
}
void ui_event_keyboardTextArea1(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_FOCUSED)
      {
            keyboard_pop_up_Animation(ui_keyboardPanel1, 0);
      }
      if (event_code == LV_EVENT_DEFOCUSED)
      {
            keyboard_hide_Animation(ui_keyboardPanel1, 0);
      }
}
void ui_event_sendButton1(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_RELEASED)
      {
            first_query_update(e);
            _ui_screen_change(&ui_MultiResponsePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MultiResponsePage_screen_init);
            send_query_to_server(e);
            // (e);
      }
}
void ui_event_Keyboard2(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_RELEASED)
      {
            _ui_keyboard_set_target(ui_Keyboard2, ui_KeyboardTextArea2);
            is_query_present(e);
      }
      if (event_code == LV_EVENT_READY)
      {
            keyboard_hide_Animation(ui_KeyboardPanel2, 0);
      }
}
void ui_event_KeyboardTextArea2(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_FOCUSED)
      {
            keyboard_pop_up_Animation(ui_KeyboardPanel2, 0);
      }
      if (event_code == LV_EVENT_DEFOCUSED)
      {
            keyboard_hide_Animation(ui_KeyboardPanel2, 0);
      }
}
void ui_event_sendButton2(lv_event_t *e)
{
      lv_event_code_t event_code = lv_event_get_code(e);
      lv_obj_t *target = lv_event_get_target(e);
      if (event_code == LV_EVENT_RELEASED)
      {
            add_new_query(e);
            send_query_to_server(e);
      }
}

///////////////////// SCREENS ////////////////////
int total_queries = 1;
void ui_init(void)
{
      lv_disp_t *dispp = lv_disp_get_default();
      lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
      lv_disp_set_theme(dispp, theme);
      ui_entryPage_screen_init();
      ui_MultiResponsePage_screen_init();
      ui____initial_actions0 = lv_obj_create(NULL);
      lv_disp_load_scr(ui_entryPage);
}
