// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#define MAX_QUERIES 100

    extern int total_queries;

    void keyboard_pop_up_Animation(lv_obj_t *TargetObject, int delay);
    void keyboard_hide_Animation(lv_obj_t *TargetObject, int delay);
    // SCREEN: ui_entryPage
    void ui_entryPage_screen_init(void);
    extern lv_obj_t *ui_entryPage;
    extern lv_obj_t *ui_chatgptdecor;
    void ui_event_Suggestion2(lv_event_t *e);
    extern lv_obj_t *ui_Suggestion2;
    void ui_event_Suggestion1(lv_event_t *e);
    extern lv_obj_t *ui_Suggestion1;
    void ui_event_keyboardPanel1(lv_event_t *e);
    extern lv_obj_t *ui_keyboardPanel1;
    void ui_event_Keyboard1(lv_event_t *e);
    extern lv_obj_t *ui_Keyboard1;
    void ui_event_keyboardTextArea1(lv_event_t *e);
    extern lv_obj_t *ui_keyboardTextArea1;
    void ui_event_sendButton1(lv_event_t *e);
    extern lv_obj_t *ui_sendButton1;
    // SCREEN: ui_MultiResponsePage
    void ui_MultiResponsePage_screen_init(void);
    extern lv_obj_t *ui_MultiResponsePage;
    extern lv_obj_t *ui_QueryResponsePanel;
    extern lv_obj_t *ui_QueryPanel;
    extern lv_obj_t *ui_querybox1;
    extern lv_obj_t *ui_queyboximg;
    extern lv_obj_t *ui_ResponsePanel;
    extern lv_obj_t *ui_Image3;
    extern lv_obj_t *ui_ResponseBox;
    extern lv_obj_t *ui_Spinner1;
    extern lv_obj_t *ui_KeyboardPanel2;
    void ui_event_Keyboard2(lv_event_t *e);
    extern lv_obj_t *ui_Keyboard2;
    void ui_event_KeyboardTextArea2(lv_event_t *e);
    extern lv_obj_t *ui_KeyboardTextArea2;
    void ui_event_sendButton2(lv_event_t *e);
    extern lv_obj_t *ui_sendButton2;
    extern lv_obj_t *ui____initial_actions0;

    extern lv_obj_t *ui_QueryBoxes[MAX_QUERIES];
    extern lv_obj_t *ui_QueryPanels[MAX_QUERIES];
    extern lv_obj_t *ui_QueryImages[MAX_QUERIES];
    extern lv_obj_t *ui_ResponseBoxes[MAX_QUERIES];
    extern lv_obj_t *ui_ResponsePanels[MAX_QUERIES];
    extern lv_obj_t *ui_ResponseImages[MAX_QUERIES];
    void create_new_query();

    LV_IMG_DECLARE(ui_img_1645855493); // assets\right-arrow-res.png
    LV_IMG_DECLARE(ui_img_116700466);  // assets\user (2).png
    LV_IMG_DECLARE(ui_img_1161678635); // assets\icons8-chatgpt-24.png

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
