// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void first_query_update(lv_event_t * e);
void send_query_to_server(lv_event_t * e);
void is_query_present(lv_event_t * e);
void add_new_query(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
