// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
// #include <lv_event.h>
// #include <lv_obj.h>
#include "lvgl.h"
#include <stdio.h>
#include <string.h>
#include "esp_log.h"
#include "wifi.h"
#include "configs.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_heap_caps.h"

typedef struct http_params
{
	char *post_data;
	char *response_data;
} http_params;

void first_query_update(lv_event_t *e)
{
	// Your code here
	// get the text from the first textarea and put it into querytextarea
	// check if this is any of the suggestions
	lv_obj_t *current = lv_event_get_target(e);
	char *text = lv_textarea_get_text(ui_keyboardTextArea1);
	lv_textarea_set_text(ui_querybox1, text);
}

void execute_http_workflow(void *params)
{
	http_params *data = (http_params *)params;

	send_http_request(data->post_data);
	get_response(data->response_data, MAX_BUFFER_LEN);

	lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);
	if (total_queries == 1)
	{
		lv_textarea_set_text(ui_ResponseBox, data->response_data);
	}
	else
	{
		lv_textarea_set_text(ui_ResponseBoxes[total_queries - 2], data->response_data);
	}
	lv_obj_scroll_to_y(ui_QueryResponsePanel, 1000, LV_ANIM_ON);

	heap_caps_free(data->post_data);
	heap_caps_free(data->response_data);
	heap_caps_free(data);

	// exit gracefully
	vTaskDelete(NULL);
}

void send_query_to_server(lv_event_t *e)
{
	char *query;
	lv_obj_t *current = lv_event_get_current_target(e);

	if (current == ui_sendButton1 || current == ui_Suggestion1 || current == ui_Suggestion2)
	{
		query = lv_textarea_get_text(ui_keyboardTextArea1);
	}
	else
	{
		query = lv_textarea_get_text(ui_KeyboardTextArea2);
	}

	char *post_data = heap_caps_malloc(512, MALLOC_CAP_SPIRAM);
	char *response_data = heap_caps_malloc(512, MALLOC_CAP_SPIRAM);

	sprintf(post_data, "{\"query\" : \"%s\"}", query);
	ESP_LOGI(REQ, "Query sent: %s", post_data);

	http_params *params = heap_caps_malloc(sizeof(http_params), MALLOC_CAP_SPIRAM);
	params->post_data = post_data;
	params->response_data = response_data;

	TaskHandle_t http_request_task = NULL;
	xTaskCreate(execute_http_workflow, "http_request_task", 4096, params, 10, &http_request_task);
}

void is_query_present(lv_event_t *e)
{

	lv_obj_t *current = lv_event_get_current_target(e);

	// compare this with keyboards in both screen
	// then enable or disable the button in the screen accordingly
	if (current == ui_Keyboard1)
	{
		// if screen1 text area has data, enable the button
		// else disable
		ESP_LOGI("INFO", "KEYBOARD1");
		if (strlen(lv_textarea_get_text(ui_keyboardTextArea1)) > 0)
		{
			lv_obj_clear_state(ui_sendButton1, LV_STATE_DISABLED);
			lv_obj_add_state(ui_sendButton1, LV_STATE_DEFAULT);
		}
		else
		{
			lv_obj_clear_state(ui_sendButton1, LV_STATE_DEFAULT);
			lv_obj_add_state(ui_sendButton1, LV_STATE_DISABLED);
		}
	}
	else if (current == ui_Keyboard2)
	{
		char *text = lv_textarea_get_text(ui_KeyboardTextArea2);
		// ESP_LOGI("INFO", "Text keyboard2 : %s len: %d", text, strlen(text));
		if (strlen(text) > 0)
		{
			lv_obj_clear_state(ui_sendButton2, LV_STATE_DISABLED);
			lv_obj_add_state(ui_sendButton2, LV_STATE_DEFAULT);
		}
		else
		{
			lv_obj_clear_state(ui_sendButton2, LV_STATE_DEFAULT);
			lv_obj_add_state(ui_sendButton2, LV_STATE_DISABLED);
		}
	}
}

void add_new_query(lv_event_t *e)
{
	// Your code here
	create_new_query();
}
